---
- name: aws | lt | build launch_template_data
  include_vars: vars/launch-template-data.yml

- name: aws | lt | update ami_id based on SPEC
  set_fact:
    lt_spec_local:
      name: "{{ item_scale.lt_name }}"
      image_id: "{{ item_scale.lt_spec.image_id }}"
      launch_template_data: "{{ launch_template_data }}"
  when: item_scale.lt_spec.image_id is defined

- name: aws | lt | create final SPEC
  set_fact:
    lt_spec: "{{
      lt_spec_local
      |combine(item_scale.lt_spec_default |d({}) )
      |combine(item_scale.lt_spec |d({}) )
    }}"

- name: aws | lt | show SPEC
  debug: var=lt_spec

- name: aws | lt | check exists
  shell: |
    aws ec2 describe-launch-templates --launch-template-name "{{ item_scale.lt_name }}"
  register: desc_result
  changed_when: False
  failed_when:
    - desc_result.rc != 0
    - desc_result.rc != 255

- name: aws | lt | create
  shell: |
    aws ec2 create-launch-template \
      --launch-template-name {{ item_scale.lt_name }} \
      --version-description '{{ lt_spec.version_description | d('Automatically generated by ansible') }}' \
      --launch-template-data '{{ lt_spec.launch_template_data | to_json }}' \
      --region {{ item_scale.region | d('us-east-1') }}
  register: lt_result
  when:
    - lt_spec is defined
    - desc_result.rc == 255
