---

- name: AMI | setup
  include: "aws-ami.yml"
  when:
    - item_scale.ami_name is defined

- name: LC | setup
  include: "aws-lc.yml"
  when:
    - item_scale.lc_name is defined
    - item_scale.lc_spec is defined

- name: ASG | setup
  include: "aws-asg.yml"
  when:
    - item_scale.asg_name is defined
    - item_scale.asg_spec is defined
