---

- name: AMI | setup
  import_tasks: "aws-ami.yml"
  when:
    - item_scale.ami_name is defined
  tags: aws-ami

- name: LC | setup
  import_tasks: "aws-lc.yml"
  when:
    - item_scale.lc_name is defined
    - item_scale.lc_spec is defined
  tags: aws-lc

- name: LT | setup
  import_tasks: "aws-lt.yml"
  when:
    - item_scale.lt_name is defined
    - item_scale.lt_spec is defined
  tags: aws-lt

- name: ASG | setup
  import_tasks: "aws-asg.yml"
  when:
    - item_scale.asg_name is defined
    - item_scale.asg_spec is defined
  tags: aws-asg
